[tool.ruff]
line-length = 110
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "__pycache__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
select = [
    "A",
    "ARG",
    "B",
    "C",
    "COM",
    "D",
    "DTZ",
    "E",
    "EM",
    "F",
    "FBT",
    "I",
    "ICN",
    "ISC",
    "N",
    "PERF",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "Q",
    "RUF",
    "TID",
    "UP",
    "W",
    "YTT"
]
ignore = [
    "COM812",
    "ISC001",
    "E402"
]
[tool.ruff.per-file-ignores]
"tests/*" = []
[tool.ruff.pydocstyle]
convention = "google"
[tool.pylint]
max-line-length = 110
disable = []  # "C0330"
[tool.black]
line-length = 110